version: "3"

services:
  pihole-unbound:
    build: .
    container_name: pihole-unbound
    image: pihole-unbound:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    environment:
      FTLCONF_REPLY_ADDR4: $PIHOLE_IP_ADDRESS
      TZ: $PIHOLE_TIMEZONE
      WEBTHEME: "default-dark"
      WEBPASSWORD: $PIHOLE_PASSWORD
      DNS1: 127.0.0.1#5335
      DNS2: 127.0.0.1#5335
      DNSSEC: "true"
      IPv6: "false"
    volumes:
      - ~/.pihole/.pihole/:/etc/pihole:rw
      - ~/.pihole/.dnsmasq.d/:/etc/dnsmasq.d:rw
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
